<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['name' => 'Москва', 'region' => 'Москва', 'region_code' => 'MOW', 'sort_order' => 1],
            ['name' => 'Санкт-Петербург', 'region' => 'Санкт-Петербург', 'region_code' => 'SPE', 'sort_order' => 2],
            ['name' => 'Новосибирск', 'region' => 'Новосибирская область', 'region_code' => 'NVS', 'sort_order' => 3],
            ['name' => 'Екатеринбург', 'region' => 'Свердловская область', 'region_code' => 'SVE', 'sort_order' => 4],
            ['name' => 'Казань', 'region' => 'Республика Татарстан', 'region_code' => 'TAT', 'sort_order' => 5],
            ['name' => 'Нижний Новгород', 'region' => 'Нижегородская область', 'region_code' => 'NIZ', 'sort_order' => 6],
            ['name' => 'Челябинск', 'region' => 'Челябинская область', 'region_code' => 'CHE', 'sort_order' => 7],
            ['name' => 'Самара', 'region' => 'Самарская область', 'region_code' => 'SAM', 'sort_order' => 8],
            ['name' => 'Омск', 'region' => 'Омская область', 'region_code' => 'OMS', 'sort_order' => 9],
            ['name' => 'Ростов-на-Дону', 'region' => 'Ростовская область', 'region_code' => 'ROS', 'sort_order' => 10],
            ['name' => 'Уфа', 'region' => 'Республика Башкортостан', 'region_code' => 'BA', 'sort_order' => 11],
            ['name' => 'Красноярск', 'region' => 'Красноярский край', 'region_code' => 'KYA', 'sort_order' => 12],
            ['name' => 'Воронеж', 'region' => 'Воронежская область', 'region_code' => 'VOR', 'sort_order' => 13],
            ['name' => 'Пермь', 'region' => 'Пермский край', 'region_code' => 'PER', 'sort_order' => 14],
            ['name' => 'Волгоград', 'region' => 'Волгоградская область', 'region_code' => 'VGG', 'sort_order' => 15],
            ['name' => 'Краснодар', 'region' => 'Краснодарский край', 'region_code' => 'KDA', 'sort_order' => 16],
            ['name' => 'Саратов', 'region' => 'Саратовская область', 'region_code' => 'SAR', 'sort_order' => 17],
            ['name' => 'Тюмень', 'region' => 'Тюменская область', 'region_code' => 'TYU', 'sort_order' => 18],
            ['name' => 'Тольятти', 'region' => 'Самарская область', 'region_code' => 'SAM', 'sort_order' => 19],
            ['name' => 'Ижевск', 'region' => 'Удмуртская Республика', 'region_code' => 'UD', 'sort_order' => 20],

            // Остальные 80 городов — по алфавиту
            ['name' => 'Абакан', 'region' => 'Республика Хакасия', 'region_code' => 'KHM', 'sort_order' => 101],
            ['name' => 'Азов', 'region' => 'Ростовская область', 'region_code' => 'ROS', 'sort_order' => 102],
            ['name' => 'Александров', 'region' => 'Владимирская область', 'region_code' => 'VLA', 'sort_order' => 103],
            ['name' => 'Альметьевск', 'region' => 'Республика Татарстан', 'region_code' => 'TAT', 'sort_order' => 104],
            ['name' => 'Ангарск', 'region' => 'Иркутская область', 'region_code' => 'IRK', 'sort_order' => 105],
            ['name' => 'Анжеро-Судженск', 'region' => 'Кемеровская область', 'region_code' => 'KEM', 'sort_order' => 106],
            ['name' => 'Апатиты', 'region' => 'Мурманская область', 'region_code' => 'MUR', 'sort_order' => 107],
            ['name' => 'Арзамас', 'region' => 'Нижегородская область', 'region_code' => 'NIZ', 'sort_order' => 108],
            ['name' => 'Армавир', 'region' => 'Краснодарский край', 'region_code' => 'KDA', 'sort_order' => 109],
            ['name' => 'Арсеньев', 'region' => 'Приморский край', 'region_code' => 'PRI', 'sort_order' => 110],
            ['name' => 'Артём', 'region' => 'Приморский край', 'region_code' => 'PRI', 'sort_order' => 111],
            ['name' => 'Астрахань', 'region' => 'Астраханская область', 'region_code' => 'AST', 'sort_order' => 112],
            ['name' => 'Балаково', 'region' => 'Саратовская область', 'region_code' => 'SAR', 'sort_order' => 113],
            ['name' => 'Балашиха', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 114],
            ['name' => 'Балашов', 'region' => 'Саратовская область', 'region_code' => 'SAR', 'sort_order' => 115],
            ['name' => 'Барнаул', 'region' => 'Алтайский край', 'region_code' => 'ALT', 'sort_order' => 116],
            ['name' => 'Белгород', 'region' => 'Белгородская область', 'region_code' => 'BEL', 'sort_order' => 117],
            ['name' => 'Бердск', 'region' => 'Новосибирская область', 'region_code' => 'NVS', 'sort_order' => 118],
            ['name' => 'Березники', 'region' => 'Пермский край', 'region_code' => 'PER', 'sort_order' => 119],
            ['name' => 'Бийск', 'region' => 'Алтайский край', 'region_code' => 'ALT', 'sort_order' => 120],
            ['name' => 'Благовещенск', 'region' => 'Амурская область', 'region_code' => 'AMU', 'sort_order' => 121],
            ['name' => 'Братск', 'region' => 'Иркутская область', 'region_code' => 'IRK', 'sort_order' => 122],
            ['name' => 'Брянск', 'region' => 'Брянская область', 'region_code' => 'BRY', 'sort_order' => 123],
            ['name' => 'Великие Луки', 'region' => 'Псковская область', 'region_code' => 'PSK', 'sort_order' => 124],
            ['name' => 'Владивосток', 'region' => 'Приморский край', 'region_code' => 'PRI', 'sort_order' => 125],
            ['name' => 'Владикавказ', 'region' => 'Республика Северная Осетия — Алания', 'region_code' => 'SE', 'sort_order' => 126],
            ['name' => 'Владимир', 'region' => 'Владимирская область', 'region_code' => 'VLA', 'sort_order' => 127],
            ['name' => 'Волгодонск', 'region' => 'Ростовская область', 'region_code' => 'ROS', 'sort_order' => 128],
            ['name' => 'Волжский', 'region' => 'Волгоградская область', 'region_code' => 'VGG', 'sort_order' => 129],
            ['name' => 'Вологда', 'region' => 'Вологодская область', 'region_code' => 'VLG', 'sort_order' => 130],
            ['name' => 'Вольск', 'region' => 'Саратовская область', 'region_code' => 'SAR', 'sort_order' => 131],
            ['name' => 'Воркута', 'region' => 'Республика Коми', 'region_code' => 'KO', 'sort_order' => 132],
            ['name' => 'Грозный', 'region' => 'Чеченская Республика', 'region_code' => 'CE', 'sort_order' => 133],
            ['name' => 'Дербент', 'region' => 'Республика Дагестан', 'region_code' => 'DA', 'sort_order' => 134],
            ['name' => 'Дзержинск', 'region' => 'Нижегородская область', 'region_code' => 'NIZ', 'sort_order' => 135],
            ['name' => 'Димитровград', 'region' => 'Ульяновская область', 'region_code' => 'ULY', 'sort_order' => 136],
            ['name' => 'Домодедово', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 137],
            ['name' => 'Егорьевск', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 138],
            ['name' => 'Железнодорожный', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 139],
            ['name' => 'Жуковский', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 140],
            ['name' => 'Забайкальск', 'region' => 'Забайкальский край', 'region_code' => 'ZAB', 'sort_order' => 141],
            ['name' => 'Златоуст', 'region' => 'Челябинская область', 'region_code' => 'CHE', 'sort_order' => 142],
            ['name' => 'Иваново', 'region' => 'Ивановская область', 'region_code' => 'IVA', 'sort_order' => 143],
            ['name' => 'Иркутск', 'region' => 'Иркутская область', 'region_code' => 'IRK', 'sort_order' => 144],
            ['name' => 'Ишим', 'region' => 'Тюменская область', 'region_code' => 'TYU', 'sort_order' => 145],
            ['name' => 'Йошкар-Ола', 'region' => 'Республика Марий Эл', 'region_code' => 'ME', 'sort_order' => 146],
            ['name' => 'Калининград', 'region' => 'Калининградская область', 'region_code' => 'KGD', 'sort_order' => 147],
            ['name' => 'Каменск-Уральский', 'region' => 'Свердловская область', 'region_code' => 'SVE', 'sort_order' => 148],
            ['name' => 'Камышин', 'region' => 'Волгоградская область', 'region_code' => 'VGG', 'sort_order' => 149],
            ['name' => 'Каспийск', 'region' => 'Республика Дагестан', 'region_code' => 'DA', 'sort_order' => 150],
            ['name' => 'Кемерово', 'region' => 'Кемеровская область', 'region_code' => 'KEM', 'sort_order' => 151],
            ['name' => 'Кинешма', 'region' => 'Ивановская область', 'region_code' => 'IVA', 'sort_order' => 152],
            ['name' => 'Киров', 'region' => 'Кировская область', 'region_code' => 'KIR', 'sort_order' => 153],
            ['name' => 'Клин', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 154],
            ['name' => 'Ковров', 'region' => 'Владимирская область', 'region_code' => 'VLA', 'sort_order' => 155],
            ['name' => 'Коломна', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 156],
            ['name' => 'Комсомольск-на-Амуре', 'region' => 'Хабаровский край', 'region_code' => 'KHA', 'sort_order' => 157],
            ['name' => 'Копейск', 'region' => 'Челябинская область', 'region_code' => 'CHE', 'sort_order' => 158],
            ['name' => 'Королёв', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 159],
            ['name' => 'Кострома', 'region' => 'Костромская область', 'region_code' => 'KOS', 'sort_order' => 160],
            ['name' => 'Котлас', 'region' => 'Архангельская область', 'region_code' => 'ARK', 'sort_order' => 161],
            ['name' => 'Красногорск', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 162],
            ['name' => 'Краснодар', 'region' => 'Краснодарский край', 'region_code' => 'KDA', 'sort_order' => 163],
            ['name' => 'Кузнецк', 'region' => 'Пензенская область', 'region_code' => 'PNZ', 'sort_order' => 164],
            ['name' => 'Курган', 'region' => 'Курганская область', 'region_code' => 'KGN', 'sort_order' => 165],
            ['name' => 'Курск', 'region' => 'Курская область', 'region_code' => 'KRS', 'sort_order' => 166],
            ['name' => 'Липецк', 'region' => 'Липецкая область', 'region_code' => 'LIP', 'sort_order' => 167],
            ['name' => 'Лобня', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 168],
            ['name' => 'Лысьва', 'region' => 'Пермский край', 'region_code' => 'PER', 'sort_order' => 169],
            ['name' => 'Лыткарино', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 170],
            ['name' => 'Магнитогорск', 'region' => 'Челябинская область', 'region_code' => 'CHE', 'sort_order' => 171],
            ['name' => 'Майкоп', 'region' => 'Республика Адыгея', 'region_code' => 'AD', 'sort_order' => 172],
            ['name' => 'Махачкала', 'region' => 'Республика Дагестан', 'region_code' => 'DA', 'sort_order' => 173],
            ['name' => 'Миасс', 'region' => 'Челябинская область', 'region_code' => 'CHE', 'sort_order' => 174],
            ['name' => 'Мончегорск', 'region' => 'Мурманская область', 'region_code' => 'MUR', 'sort_order' => 175],
            ['name' => 'Московский', 'region' => 'Москва', 'region_code' => 'MOW', 'sort_order' => 176],
            ['name' => 'Мурманск', 'region' => 'Мурманская область', 'region_code' => 'MUR', 'sort_order' => 177],
            ['name' => 'Мытищи', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 178],
            ['name' => 'Набережные Челны', 'region' => 'Республика Татарстан', 'region_code' => 'TAT', 'sort_order' => 179],
            ['name' => 'Находка', 'region' => 'Приморский край', 'region_code' => 'PRI', 'sort_order' => 180],
            ['name' => 'Невинномысск', 'region' => 'Ставропольский край', 'region_code' => 'STA', 'sort_order' => 181],
            ['name' => 'Нефтекамск', 'region' => 'Республика Башкортостан', 'region_code' => 'BA', 'sort_order' => 182],
            ['name' => 'Нефтеюганск', 'region' => 'Ханты-Мансийский автономный округ', 'region_code' => 'KHM', 'sort_order' => 183],
            ['name' => 'Нижневартовск', 'region' => 'Ханты-Мансийский автономный округ', 'region_code' => 'KHM', 'sort_order' => 184],
            ['name' => 'Нижнекамск', 'region' => 'Республика Татарстан', 'region_code' => 'TAT', 'sort_order' => 185],
            ['name' => 'Новокузнецк', 'region' => 'Кемеровская область', 'region_code' => 'KEM', 'sort_order' => 186],
            ['name' => 'Новомосковск', 'region' => 'Тульская область', 'region_code' => 'TUL', 'sort_order' => 187],
            ['name' => 'Новороссийск', 'region' => 'Краснодарский край', 'region_code' => 'KDA', 'sort_order' => 188],
            ['name' => 'Новочебоксарск', 'region' => 'Чувашия', 'region_code' => 'CU', 'sort_order' => 189],
            ['name' => 'Новочеркасск', 'region' => 'Ростовская область', 'region_code' => 'ROS', 'sort_order' => 190],
            ['name' => 'Новый Уренгой', 'region' => 'Ямало-Ненецкий автономный округ', 'region_code' => 'YAN', 'sort_order' => 191],
            ['name' => 'Ногинск', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 192],
            ['name' => 'Обнинск', 'region' => 'Калужская область', 'region_code' => 'KLU', 'sort_order' => 193],
            ['name' => 'Одинцово', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 194],
            ['name' => 'Октябрьский', 'region' => 'Республика Башкортостан', 'region_code' => 'BA', 'sort_order' => 195],
            ['name' => 'Орёл', 'region' => 'Орловская область', 'region_code' => 'ORL', 'sort_order' => 196],
            ['name' => 'Оренбург', 'region' => 'Оренбургская область', 'region_code' => 'ORE', 'sort_order' => 197],
            ['name' => 'Орехово-Зуево', 'region' => 'Московская область', 'region_code' => 'MOS', 'sort_order' => 198],
            ['name' => 'Пенза', 'region' => 'Пензенская область', 'region_code' => 'PNZ', 'sort_order' => 199],
            ['name' => 'Первоуральск', 'region' => 'Свердловская область', 'region_code' => 'SVE', 'sort_order' => 200],
        ];

        \Illuminate\Support\Facades\DB::table('cities')->insert($cities);
    }
}
